### ISSUE TITLE
update available tiles

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/addPmData#8]
There are some more tiles completed and ready to download.  I'm querying which ones are available by using this code:

```r
safe_harbor_h3 <- readRDS("us_h3_3_population_20k_minimum_hex_ids.rds")

# use 2020 to check if all years are avail
safe_s3_check <- function(h3 = cincinnati_h3_3s[85]) {
  s3_uris <- paste0("s3://pm25-brokamp/", h3, "_2020_h3pm.fst")
  safe_check <- purrr::possibly(s3:::s3_check_for_file_s3, otherwise = FALSE)
  safe_check(s3_uris)
}

safe_harbor_h3_avail <- purrr::map_lgl(safe_harbor_h3, safe_s3_check)

safe_harbor_h3[safe_harbor_h3_avail]
```

copy/paste'able output here: ...

```r
R > dput(safe_harbor_h3[safe_harbor_h3_avail])

c("834453fffffffff", "834451fffffffff", "832ab5fffffffff", "83270bfffffffff", 
"832ab3fffffffff", "832806fffffffff", "832b1efffffffff", "832709fffffffff", 
"832ab1fffffffff", "834883fffffffff", "832802fffffffff", "832b1afffffffff", 
"834881fffffffff", "83276efffffffff", "8344d5fffffffff", "83441efffffffff", 
"8344aefffffffff", "8344f6fffffffff", "83276afffffffff", "8344d1fffffffff", 
"83291afffffffff", "8344acfffffffff", "8344f4fffffffff", "832a15fffffffff", 
"832768fffffffff", "832b10fffffffff", "83441afffffffff", "832a13fffffffff", 
"832a36fffffffff", "8344a8fffffffff", "8344f0fffffffff", "8312dafffffffff", 
"832a34fffffffff", "8312d8fffffffff", "832ab6fffffffff", "832ab2fffffffff", 
"832ab0fffffffff", "832749fffffffff", "83274dfffffffff", "832a90fffffffff", 
"832a91fffffffff", "832a92fffffffff", "832a93fffffffff", "832a94fffffffff", 
"832a96fffffffff", "832a98fffffffff", "832a9afffffffff", "832a9cfffffffff", 
"832a9efffffffff", "832661fffffffff", "832665fffffffff", "832668fffffffff", 
"832669fffffffff", "83266cfffffffff", "83266dfffffffff", "83266efffffffff"
)
```

... that we can use to update the availability check here:

https://github.com/geomarker-io/addPmData/blob/9a0958765b13bb51f1bfe111257a4817618c0921/R/add_pm_data.R#L69-L74

I expect the tiles to be updated periodically, so that more and more of them will become available over time.  It might make sense to convert this error into a warning?  ... just in case estimates are freshly available, but not accessible because the hard coded "filter" in the package thinks they are not.

**Comment by cole-brokamp** [comment]
and a quick mapview screenshot for visual reference:

```r
safe_harbor_h3[safe_harbor_h3_avail] %>%
  h3::h3_to_geo_boundary_sf() %>%
  mapview::mapview()
```

![image](https://user-images.githubusercontent.com/4367617/114602121-3da7c580-9c64-11eb-8444-700f26a424f7.png)

**Comment by erikarasnick** [comment]
should I build the check into the package? Or just change the list of available tiles by copy/paste?

**Comment by cole-brokamp** [comment]
The check takes a little too long to run every time.  Let's update it manually right now, but make sure that it is a warning and non an error if the function calls an unavailable tile.  (It should error anyway if the tile doesn't exist on S3.)
